### ISSUE TITLE
Tubehax?

### ISSUE THREAD

**Issue by Defaction** [zeta0134/3ds-homebrew-browser#16]
I've recently started using tubehax and I attempted to install homebrew browser but its not showing up. Am I installing it improperly? or is homebrew browser not supported on tubehax atm?

**Comment by Defaction** [comment]
nvm I download the source files instead of the correct files -_(\

**Comment by zeta0134** [comment]
Oh? I'm glad to hear it's working; newer versions of ninjhax have been breaking it recently. I'll do some tests later today if I get a chance. Thanks for the heads up anyway. :)
